# First Exercise: The basics!

In this notebook we'll briefly go over some of the parts of python we'll be using this week. It's important to note that I'm skipping over some of the main philisophical components of coding. If you're just seeing code for the first time, I don't want this to be overwhelming! I'm hoping that by only introducing what we'll be using this week, it'll make it less intimidating. Just know that this little bit of code we'll be using represents such a tiny part of the universe of coding! 

# Important: 
Double click this "cell" and type your team name below.

**Team Name Goes Here**

## Importing Libraries

First we'll learn how to import libraries. Libraries are packages of code that other people have written and shared to help other users have cleaner and more efficient code. They include definitions for complicated pieces of code called _functions_ and defined _objects_ so that users can "call" on the functions instead of rewriting everything!

Imagine we wanted to import a package called `affection` because we wanted to use the function `hug`.  The first thing we would do is import the package by typing `import affection`.
     
Then (assuming we had an object defined named `Izzy`) if we wanted to use the `hug()` function we would just type `affection.hug(Izzy)`.

If typing `affection` was too long we could give it a nickname by typing `import affection as aff`. Once we've nicknamed the package, to use the hug function we would just need to write `aff.hug(Izzy)`.

Say the `affection` package contains the functions `hug`, `hold_hands`, and `high_five`, but we know we will just use the `hug` function for our program. In that case, we can just type `import affection.hug` and then to use it we would just need to write `hug(Izzy)`.

The three packages we'll be using this week are `numpy`, `networkx`, and `matplotlib`. They will help us store, analyze, and visualize networks.

### What is `numpy`?

In [1]:
import numpy as np

The package `numpy` is short for "numerical python". It's a package that contains a lot of helpful tools for doing computational mathematics. We'll just be using _numpy arrays_ which will help us store data about networks. Note that here I gave `numpy` the nickname, `np`. This is a common nickname for the `numpy` package and you'll probably see it online!

### What is `networkx`?

In [2]:
import networkx as nx

This week we'll be learning about these amazing things called _networks_ which tell us about the relationships between certain objects (like humans, chemicals, or trains). The package `networkx` has been developed specifically for understanding these things! 

### What is `matplotlib`?

In [3]:
import matplotlib.pyplot as plt

The package `matplotlib` contains lots of tools for visulizing data in python. The specific part we're loading, `pyplot` will help us plot networks. The nickname `plt` is commonly used for the `pyplot` part of the `matplotlib` package.

## Matrices and arrays

As we'll talk about tomorrow, the main mathematical object related to networks are called _adjacency matrices_. Don't worry if you've never heard about them before! We'll be able to talk through it all tomorrow. To gain a bit of familiarity, it's helpful to think of matrices as the math-y version of tables. 

For example, imagine we have a table of values:

**<div align="center"> What did you eat yesterday?</div>**

| Name | Number of sandwiches eaten | Number of grapes eaten | Number of cookies eaten |
| --- | --- | --- | --- |
| Izzy | 3 | 24 | 6 |
| Shivani | 2 | 8 | 3 |
| Malcolm | 1 | 0 | 15 |
| Sherry | 2 | 11 | 3 |

If we wanted to represent this table as a _matrix_, it would look like this:

$$\begin{bmatrix} 3 & 24 & 6 \\ 2 & 8 & 3 \\ 1 & 0 & 15 \\ 2 & 11 & 3 \end{bmatrix}$$

Notice that the row and column names are now implied rather than being explicit as they are in the table. It's still important to maintain an understanding of _what_ a matrix represents, and oftentimes this means having discipline-specific experts to collaborate with.

In the following chunk of code, we'll learn how to create this same matrix as an array using `numpy`.

## Creating a matrix using `numpy`
We'll create a `numpy` array named `Ate_Yesterday` to represent the matrix we defined above.

In [60]:
Ate_Yesterday = np.array([ [3, 24, 6], [2, 8, 3], [1, 0, 15], [2, 11, 3] ])

print(Ate_Yesterday)

[[ 3 24  6]
 [ 2  8  3]
 [ 1  0 15]
 [ 2 11  3]]


If we were worried about remembering what the name of the columns or rows of the table were, we could create arrays to help us:

In [64]:
columns = np.array([ 'Sandwiches', 'Grapes', 'Cookies' ])
rows = np.array([ 'Izzy', 'Shivani', 'Malcolm', 'Sherry' ])

### Zero-indexing in Python
If you've never used python before, a really important thing to know is that _everything_ is "zero-indexed". This means that the _first_ of any list or array is the "zero-th" element. 

So if we wanted to know the first row in the table, we would type `print(rows[0])`

In [6]:
print(rows[0])

Izzy


### Accessing and editing elements of a matrix

What if we wanted to know how many cookies Shivani ate yesterday? Since Shivani is the _second_ row in the table, we know her corresponding row in the matrix is `1`. Since cookies are the _third_ column in the table, we know the corresponding column in the matrix is `2`. In math, we'd say we want to know the (1,2) element of the matrix. To do so, we would type `print( Ate_Yesterday[1,2])`.

In [7]:
print(Ate_Yesterday[1, 2])

3


When we type brackets `[]` next to the matrix, we are telling python we want to access some value of the matrix. Notice that the row number always goes first, and the column number second. In this same way we can rewrite elements of the matrix!

Let's say that I realized I had mis-counted and remembered that I actually ate 14 cookies yesterday. If we wanted to update our matrix to reflect this (without re-creating the entire thing!) we could do so by re-writing the (0, 2) element of the matrix:

In [10]:
Ate_Yesterday[0, 2] = 14
print(Ate_Yesterday[0, 2])

14


What if I wanted to know everything that Malcolm ate yesterday? I _could_ ask to print each individual element of his corresponding row by typing `print(Ate_Yesterday[2, 0], Ate_Yesterday[2, 1], Ate_Yesterday[2, 2])`. This is a bit annoying! Another approach would be to use what I like to call the "all-symbol" in python, `:`. If I wanted to print _all_ of Malcolm's row, I could instead type `print(Ate_Yesterday[2, :])`!

In [12]:
print(Ate_Yesterday[2, 0], Ate_Yesterday[2, 1], Ate_Yesterday[2, 2])

print(Ate_Yesterday[2, :])

1 0 15
[ 1  0 15]


We can use the "all-symbol" for columns, too! If I wanted to know how many grapes each person ate yesterday, I could write `print(Ate_Yesterday[:, 1])`

In [13]:
print(Ate_Yesterday[:, 1])

[24  8  0]


## Reading in an array from a file
What if we're given a table as a file? It would be silly to individually type out the array as we did above. What if there were hundreds of columns? What if we made a mistake? Here we'll learn how to read in a `.csv` file to avoid that issue!


Let's say I have the file `Ate_Yesterday.csv` saved in my computer. If I save it to the same location I'm running this notebook from, I can just type:

In [62]:
folder = ""
file = "Ate_Yesterday"
ext = ".csv"
Ate_Yesterday = np.genfromtxt(folder+file+ext, dtype=int, delimiter=',', skip_header=True)

We're using a numpy function called `genfromtxt` with four parameters. The string `folder + file + ext` tells the function where the file you're looking for is and what it's called. `dtype = int` tells the function that the data type of the numpy array should be integers. `delimiter = ','` tells the function that the numbers in the table are "column separated", which is the default for tables exported to a `.csv` file. `skip_header = True` tells the function that there are headers in the table and that they should be skipped!

In [63]:
print(Ate_Yesterday)

[[ 3 24  6]
 [ 2  8  3]
 [ 1  0 15]
 [ 2 11  3]]


## Printing the shape of a matrix
What if we want to make sure what the size of our matrix is? Use the `np.shape()` function.

In [69]:
np.shape(Ate_Yesterday)

(4, 3)

If you want to know the length of a one-dimensional array or a list, an easy way to do this is by using the `len()` function.

In [70]:
len(columns)

3

## Initializing a matrix
What if I don't know what values I want in my matrix, but I want to create it so it's easier to fill in later? To do this, it's nice to use the `zeros()` function. To use it, you just need to type `np.zeros( (n,m) )` where `n` is the number of rows you'd like to have and `m` is the number of columns.

In [65]:
empty = np.zeros( (4,3) )
print(empty)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## What's Next?

Tomorrow we'll go over networks, how to use matrices to represent them, and how the packages `networkx` and `matplotlib` can help us understand and visualize them.

If you're using Jupyter Notebooks on your laptop (instead of through the browser), make sure you download the `networkx` package by following these instructions! https://networkx.org/documentation/stable/install.html

If you're not sure if you need to download `networkx`, check to see if the following line of code gives you an error message. If it does, you'll need to download it. 

In [11]:
import networkx as nx

# Task: 
Once you've finished this notebook, make sure you edit the top cell to add your team name. When you're done, select File -> Download As -> Notebook (.ipynb). **Then upload this file to your team's workspace in Teams and tag your tutor.** This will show us that you've walked through this notebook and have successfully gotten your Jupyter notebook set up. 

Also, don't forget to fill out the network survey! Link in Day 1 channel for Teams.

## Challenge
This is optional! 

Above we accessed elements of the matrix using indices `Ate_Yesterday[2, 1]` told us how many grapes Malcolm ate yesterday. Can you think of a way to access elements of the matrix just using the lists `columns` and `rows`, the names `Izzy`, `Shivani`, `Malcolm`, and `Sherry`, and the food items `Sandwiches`, `Grapes`, and `Cookies`?